development:
  adapter: postgresql
  encoding: unicode
  database: play-tasks_development
  pool: 5
  host: postgres
  username: postgres
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: play-tasks_test
  pool: 5
  host: postgres
  username: postgres
  password:

production:
  adapter: postgresql
  encoding: unicode
  database: play-tasks_production
  pool: 5
  username: postgres
  password:
