# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4a0616b81bb194273818d30d7ce21fd03b234f4fe5e6a06b9fab386729833eb6809948b523101d72b41a85a95c695a1de044dc9de6bbf74fb557de108303e45

test:
  secret_key_base: 5411e70c3c352b37a83f1280bdde2aa6783e7a6acafaa4a7a6c59633d44c539aa532370ab9c5f0864f07541ac3834bbad561ee16cab0e148459d7bf935d78067

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
